### ISSUE TITLE
Uncaught TypeError: Cannot read property 'instance' of undefined

### ISSUE THREAD

**Issue by Matmo10** [rangle/augury#1039]
Augury version (required): 1.4.0
Angular version (required): v4 rc4
Date: 3/22/17
OS: OS X

Description of issue:
```
zone.js:169 Uncaught TypeError: Cannot read property 'instance' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:7030:64
    at Array.forEach (native)
    at _parse (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:7028:17)
    at Object.exports.parseModulesFromRouter (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:7036:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9566:26
    at Array.forEach (native)
    at updateLazyLoadedNgModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9565:14)
    at updateRouterTree (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9582:10)
    at SafeSubscriber._next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9599:10)
    at SafeSubscriber.__tryOrUnsub (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:537:17)
    at SafeSubscriber.next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:486:23)
    at Subscriber._next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:439:27)
    at Subscriber.next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:403:19)
    at DebounceTimeSubscriber.debouncedNext (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:8680:31)
    at AsyncAction.dispatchNext (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:8696:17)
```

![screen shot 2017-03-21 at 11 08 26 am](https://cloud.githubusercontent.com/assets/2548215/24221175/7b8f6d94-0f0a-11e7-9712-36b2cb63b1b2.png)

**Comment by Matmo10** [comment]
I have a lazy loaded route..I use ngrx/store, ngrx/effects, etc.  I use the angular-cli.   Not sure what else you need to know :)

**Comment by olaf89** [comment]
I have the same issue :(

**Comment by MrFranke** [comment]
+1
