### ISSUE TITLE
"No provider for Router" error

### ISSUE THREAD

**Issue by fullstackfool** [rangle/augury#1216]
Augury version (required): 1.14.0
Angular version (required): 2.4.10
Angular router: 3.4.10
Date: 03/07/2017
OS: Win10 & Mac 10.11.6 

Description of issue:

```
Error: No provider for Router!
    at NoProviderError.BaseError [as constructor] (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:1341:1), <anonymous>:30:27)
    at NoProviderError.AbstractProviderError [as constructor] (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:2406:1), <anonymous>:64:16)
    at new NoProviderError (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:2406:1), <anonymous>:126:16)
    at ReflectiveInjector_._throwOrNull (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3541:1), <anonymous>:492:19)
    at ReflectiveInjector_._getByKeyDefault (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3541:1), <anonymous>:531:25)
    at ReflectiveInjector_._getByKey (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3541:1), <anonymous>:463:25)
    at ReflectiveInjector_.get (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3541:1), <anonymous>:332:21)
    at NotificationBarModuleInjector.NgModuleInjector.get (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:2447:1), <anonymous>:146:52)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3583:1), <anonymous>:165:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (eval at <anonymous> (http://app.site.dev/js/app/vendor.js:3583:1), <anonymous>:593:49)
```

The compilation works, the app works, the routing works. The app files themselves have not changed, just the compilation. I understand this isn't terribly descriptive, sorry.

Any guidance or ideas would be greatly appreciated. I've included the webpack file below:

````javascript // Helper: root() is defined at the bottom
var path = require('path');
var webpack = require('webpack');

// Webpack Plugins
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;
var autoprefixer = require('autoprefixer');
var WebpackNotifierPlugin = require('webpack-notifier');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

/**
 * Env
 * Get npm lifecycle event to identify the environment
 */
var ENV = process.env.npm_lifecycle_event;

var isTestWatch = ENV === 'test-watch';
var isTest = ENV === 'test' || isTestWatch;
var isProd = ENV === 'build:production';

module.exports = function makeWebpackConfig() {
    /**
     * Config
     * Reference: http://webpack.github.io/docs/configuration.html
     * This is the object where all configuration gets set
     */
    var config = {};

    /**
     * Devtool
     * Reference: http://webpack.github.io/docs/configuration.html#devtool
     * Type of sourcemap to use per build type
     */
    if (isProd) {
        config.devtool = 'nosources-source-map';
    }
    else if (isTest) {
        config.devtool = 'inline-source-map';
    }
    else {
        config.devtool = 'eval-source-map';
    }

    if (!isTest) {
        /**
         * Entry
         * Reference: http://webpack.github.io/docs/configuration.html#entry
         */
        config.entry = isTest ? {} : {
            'polyfills': root('angular/src/bootstrappers/polyfills.ts'),
            'vendor': root('angular/src/bootstrappers/vendor.ts'),

            'address-book': root('angular/src/bootstrappers/address-book.ts')
        };
    }

    /**
     * Output
     * Reference: http://webpack.github.io/docs/configuration.html#output
     */
    config.output = isTest ? {} : {
        path: isProd ? root('public/js/dist') : root('public/js/app'),
        filename: '[name].js',
        chunkFilename: '[id].chunk.js'
    };

    /**
     * Resolve
     * Reference: http://webpack.github.io/docs/configuration.html#resolve
     */
    config.resolve = {
        // only discover files that have those extensions
        extensions: ['.ts', '.js', '.css', '.html'],
    };

    var atlOptions = '';
    if (isTest && !isTestWatch) {
        // awesome-typescript-loader needs to output inlineSourceMap for code coverage to work with source maps.
        atlOptions = 'inlineSourceMap=true&sourceMap=false';
    }

    /**
     * Loaders
     * Reference: http://webpack.github.io/docs/configuration.html#module-loaders
     * List: http://webpack.github.io/docs/list-of-loaders.html
     * This handles most of the magic responsible for converting modules
     */
    config.module = {
        rules: [
            // Support for .ts files.
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader'],
                exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
            },

            // copy those assets to output
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'file-loader?name=fonts/[name].[hash].[ext]?'
            },

            // Support for CSS as raw text
            // use 'null' loader in test mode (https://github.com/webpack/null-loader)
            // all css in src/style will be bundled in an external css file
            {
                test: /\.css$/,
                exclude: root('src', 'app'),
                loader: isTest ? 'null-loader' : ExtractTextPlugin.extract({ fallback: 'style-loader', use: ['css-loader', 'postcss-loader']})
            },
            // all css required in src/app files will be merged in js files
            {test: /\.css$/, include: root('src', 'app'), loader: 'raw-loader!postcss-loader'},

            // support for .html as raw text
            // todo: change the loader to something that adds a hash to images
            {test: /\.html$/, loader: 'raw-loader',  exclude: root('src', 'public')}
        ]
    };

    /**
     * Plugins
     * Reference: http://webpack.github.io/docs/configuration.html#plugins
     * List: http://webpack.github.io/docs/list-of-plugins.html
     */
    config.plugins = [
        // Define env variables to help with builds
        // Reference: https://webpack.github.io/docs/list-of-plugins.html#defineplugin
        new webpack.DefinePlugin({
            // Environment helpers
            'process.env': {
                ENV: JSON.stringify(ENV)
            }
        }),

        // Workaround needed for angular 2 angular/angular#11580
        new webpack.ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)@angular/,
            root('./src') // location of your src
        ),

        new WebpackNotifierPlugin({
            alwaysNotify: true,
            excludeWarnings: true,
        }),

        // Tslint configuration for webpack 2
        new webpack.LoaderOptionsPlugin({
            options: {
                /**
                 * Apply the tslint loader as pre/postLoader
                 * Reference: https://github.com/wbuchwalter/tslint-loader
                 */
                tslint: {
                    emitErrors: false,
                    failOnHint: false
                },
                /**
                 * Sass
                 * Reference: https://github.com/jtangelder/sass-loader
                 * Transforms .scss files to .css
                 */
                sassLoader: {
                    //includePaths: [path.resolve(__dirname, "node_modules/foundation-sites/scss")]
                },
                /**
                 * PostCSS
                 * Reference: https://github.com/postcss/autoprefixer-core
                 * Add vendor prefixes to your css
                 */
                postcss: [
                    autoprefixer({
                        browsers: ['last 2 version']
                    })
                ]
            }
        })
    ];

    if (!isTest && !isTestWatch) {
        config.plugins.push(
            // Generate common chunks if necessary
            // Reference: https://webpack.github.io/docs/code-splitting.html
            // Reference: https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin
            new CommonsChunkPlugin({
                name: ['vendor', 'polyfills']
            }),

            // Extract css files
            // Reference: https://github.com/webpack/extract-text-webpack-plugin
            // Disabled when in test mode or not in build mode
            new ExtractTextPlugin({filename: 'css/[name].[hash].css', disable: !isProd})
        );
    }

    // Add build specific plugins
    if (isProd) {
        config.plugins.push(
            // Reference: http://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin
            // Only emit files when there are no errors
            new webpack.NoEmitOnErrorsPlugin(),

            // Reference: http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
            // Minify all javascript, switch loaders to minimizing mode
            new webpack.optimize.UglifyJsPlugin({sourceMap: true, mangle: { keep_fnames: true }})
        );
    }

    /**
     * Dev server configuration
     * Reference: http://webpack.github.io/docs/configuration.html#devserver
     * Reference: http://webpack.github.io/docs/webpack-dev-server.html
     */
    config.devServer = {
        contentBase: './src/public',
        historyApiFallback: true,
        quiet: true,
        stats: 'minimal' // none (or false), errors-only, minimal, normal (or true) and verbose
    };

    return config;
}();

// Helper functions
function root(args) {
    args = Array.prototype.slice.call(arguments, 0);
    return path.join.apply(path, [__dirname].concat(args));
} ```

**Comment by fullstackfool** [comment]
This seems to have resolved itself. Possibly due to a compilation issue on a specific branch.

**Comment by fullstackfool** [comment]
Apologies, when found to be working it was tested on root page of SPA, hence no router issues. Any internal pages give same issue
