### ISSUE TITLE
Exception with the latest build which I had installed long ago and updated automatically to 1.16

### ISSUE THREAD

**Issue by talamaska** [rangle/augury#1299]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): 1.16
Angular version (required): 5.2.10
Date: 2 May 2018
OS: Windows 10

Description of issue:
```
 Error: Uncaught (in promise): Error: Failed to read message queue: Error: Code evaluation failed
    at handler (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:148435:30)
    at callbackWrapper (<anonymous>:52:1)
    at ExtensionServerClient._onCallback (<anonymous>:66:653)
    at ExtensionServerClient._onMessage (<anonymous>:67:9)
Error: Failed to read message queue: Error: Code evaluation failed
    at handler (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:148435:30)
    at callbackWrapper (<anonymous>:52:1)
    at ExtensionServerClient._onCallback (<anonymous>:66:653)
    at ExtensionServerClient._onMessage (<anonymous>:67:9)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:148426:20
    at ZoneDelegate.invoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152025:27)
    at Object.onInvoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:5623:34)
    at ZoneDelegate.invoke (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152024:33)
    at Zone.run (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:151775:44)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152506:58
    at ZoneDelegate.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152058:32)
    at Object.onInvokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:5614:34)
    at ZoneDelegate.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152057:37)
    at Zone.runTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:151825:48)
    at resolvePromise (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152457:32)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152509:18
    at ZoneDelegate.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152058:32)
    at Object.onInvokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:5614:34)
    at ZoneDelegate.invokeTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152057:37)
    at Zone.runTask (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:151825:48)
    at drainMicroTaskQueue (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:152235:36)
```

**Comment by santiago-elustondo** [comment]
Thanks for reporting this. Looking into it.

**Comment by santiago-elustondo** [comment]
Could you provide some more details here?
Does this error arise on startup, or as a result of an action?

**Comment by santiago-elustondo** [comment]
closing due to lack of detail, please reopen if issue persists.
