### ISSUE TITLE
Unhandled Promise rejection: Can't resolve all parameters for XXXXXX

### ISSUE THREAD

**Issue by elboukhari** [rangle/augury#1307]
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): 1.16.1 AND 1.16.2
Angular version (required): 5.2.1
Date: 17.05.2018
OS: Debian Linux

-- Please make sure you're using the latest version of Augury before reporting an issue.
YES
Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.
When enabled it crash : 
`zone.js:665 Unhandled Promise rejection: Can't resolve all parameters for RouterPathService: (?). ; Zone: angular ; Task: Promise.then ; Value: Error: Can't resolve all parameters for RouterPathService: (?).
    at syntaxError (compiler.js:485)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:15692)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:15527)
    at CompileMetadataResolver._getInjectableMetadata (compiler.js:15507)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:15867)
    at eval (compiler.js:15778)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (compiler.js:15738)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15306)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:15125)
    at eval (compiler.js:15223)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15201)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:15125)
    at eval (compiler.js:15223)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15201)
    at JitCompiler._loadModules (compiler.js:34398)
    at JitCompiler._compileModuleAndComponents (compiler.js:34359)
    at JitCompiler.compileModuleAsync (compiler.js:34253)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:239)
    at eval (core.js:6554)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4733)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at eval (zone.js:872)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595) Error: Can't resolve all parameters for RouterPathService: (?).
    at syntaxError (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:706:34)
    at CompileMetadataResolver._getDependenciesMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15913:35)
    at CompileMetadataResolver._getTypeMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15748:26)
    at CompileMetadataResolver._getInjectableMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15728:21)
    at CompileMetadataResolver.getProviderMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:16088:40)
    at eval (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15999:49)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15959:19)
    at CompileMetadataResolver.getNgModuleMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15527:50)
    at CompileMetadataResolver.getNgModuleSummary (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15346:52)
    at eval (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15444:72)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15422:49)
    at CompileMetadataResolver.getNgModuleSummary (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15346:52)
    at eval (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15444:72)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:15422:49)
    at JitCompiler._loadModules (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:34619:87)
    at JitCompiler._compileModuleAndComponents (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:34580:36)
    at JitCompiler.compileModuleAsync (webpack-internal:///./node_modules/@angular/compiler/esm5/compiler.js:34474:37)
    at CompilerImpl.compileModuleAsync (webpack-internal:///./node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:254:49)
    at eval (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6768:60)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388:26)
    at Object.onInvoke (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4947:33)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:387:32)
    at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:138:43)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:872:34)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4938:33)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:595:35)
api.onUnhandledError @ zone.js:665
handleUnhandledRejection @ zone.js:692
_loop_1 @ zone.js:682
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
resolvePromise @ zone.js:808
(anonymous) @ zone.js:724
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ operation-management.module.chunk.js:1`

Steps to reproduce:

1. Enable Augury
2. Connect to your app --> Crash
3. Disable Augury --> Works !

Additional details:

**Comment by grumpy-programmer** [comment]
workaround is downgrading to 1.16.0 by https://crx.dam.io/ext/elgalmkoelokbchhkhacckoklkejnhcd.html (rename .zip to .crx and install)

**Comment by mxchange** [comment]
Same issue here it seems: https://github.com/angular/angular-cli/issues/5007

**Comment by jaj1014** [comment]
Having the same issue - currently on 5.2.7 of Angular

**Comment by s001dxp** [comment]
Since the update yesterday my angular application is broke. IT works when augury is disabled, and breaks when it's enabled. It took me and my co-worker most of the day trying to debug before we realized that it was Augury breaking the app.

Using Angular version 4.3.6 and Augury 1.16.2

**Comment by williamchristophercooley** [comment]
yep, this just happened to our whole team out of nowhere, and thought it was a missing Inject() issue, but it turns out it's the Augury plugin after reverting our code back to run it.

**Comment by santiago-elustondo** [comment]
Augury rolled back to 1.16.0 until this issue is resolved.
1.16.3 is a rollback release.

**Comment by santiago-elustondo** [comment]
A new version of the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) (1.17.0) is released, with what we believe might be a fix for this issue. 

reflect-metadata has been removed from the bundle. Angular uses reflect-metadata for its JIT compilations, and a versioning conflict was occurring for some users. We now piggyback off of Angular's global reflect-metadata polyfill.

@elboukhari , @williamchristophercooley , @s001dxp , @jaj1014 , @mxchange , can you confirm / disconfirm that version 1.17.0 of the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) fixes the issue?

**Comment by santiago-elustondo** [comment]
A new version of the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) (1.17.0) is released, with what we believe might be a fix for this issue. 

reflect-metadata has been removed from the bundle. Angular uses reflect-metadata for its JIT compilations, and a versioning conflict was occurring for some users. We now piggyback off of Angular's global reflect-metadata polyfill.

@elboukhari , @williamchristophercooley , @s001dxp , @jaj1014 , @mxchange , can you confirm / disconfirm that version 1.17.0 of the [Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji) fixes the issue?

**Comment by andriychuma** [comment]
The problem went away with Canary Build (1.17.0). I'm on Angular 6.0.1.

**Comment by santiago-elustondo** [comment]
Canary merged with master as official 1.18 release.
