### ISSUE TITLE
Issue while Demo test application

### ISSUE THREAD

**Issue by agalchavijaycalls** [rangle/augury#1383]
Augury: 1.23.0
Date: Sat, 06 Apr 2019 09:11:45 GMT
OS: MacIntel

Demo test application:
-- https://augury.rangle.io/examples/input-output/app/index.html.

Description of issue:
-- Include (clipped) screenshot images if possible.

TypeError: Cannot read property 'subscribe' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261926
    at M (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260124)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261814
    at ZoneDelegate.invoke (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75633:26)
    at Zone.run (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75425:43)
    at https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:76012:57
    at ZoneDelegate.invokeTask (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75666:31)
    at Zone.runTask (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75465:47)
    at drainMicroTaskQueue (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75845:35)
    at ZoneTask.invoke (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75723:25)
    at data.args.(anonymous function) (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:76880:29)

**Comment by killa-kyle** [comment]
Getting same error on the 'Tour of Heroes' tutorial app as well as 
-- https://augury.rangle.io/examples/input-output/app/index.html.

**Comment by CJ42** [comment]
I have the same issue. For online demo app built with Angular Framework, it returns either one the two messages :
- `TypeError: Cannot read property 'subscribe' of undefined`
- ` This application is running in production mode and therefore cannot be inspected using Augury. `

However, using the Chrome or Firefox extension for an Angular app built locally, it seems to work.

**Comment by Jimit09** [comment]
The above issue still persists:-

Following is the log in Augury tab of Chrome dev tools:-
TypeError: Cannot read property 'subscribe' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261926
    at M (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260124)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261814
    at ZoneDelegate.invoke (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75633:26)
    at Zone.run (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75425:43)
    at https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:76012:57
    at ZoneDelegate.invokeTask (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75666:31)
    at Zone.runTask (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75465:47)
    at drainMicroTaskQueue (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75845:35)
    at ZoneTask.invoke (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:75723:25)
    at data.args.<computed> (https://augury.rangle.io/examples/input-output/app/vendor.bundle.js:76880:29)

In console tab:-
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    at Object.t.messageJumpContext (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:9921)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:8583
t.messageJumpContext @ content-script.js:24
(anonymous) @ content-script.js:24

**Comment by mmezei** [comment]
Same issue for me. Thanks.

**Comment by myasul** [comment]
Same issue is happening for me as well.

![image](https://user-images.githubusercontent.com/25900564/61940318-c29e0780-afc7-11e9-8b11-55a3ff93c6f6.png)

**Comment by LSTANCZYK** [comment]
+1

**Comment by francoisdutoit** [comment]
+1

**Comment by OneSolutionsGitOps** [comment]
+1

**Comment by bebeto84** [comment]
Same happens here! Before I tried on some applications I have and thought it was my problem...then I came to the DEMO page and see that the problem is general.
Is there any way to make it work? Or there are any problems with Angular versions?

**Comment by bebeto84** [comment]
I've seen that latest commit was on 1st of May, so... is the project still maintained?

**Comment by feeloor** [comment]
We see this issue on `Angular < 4`. 
We leverage the `ApplicationRef.isStable` Observable, which was introduced in [this commit](https://github.com/angular/angular/commit/c4817988cad2b097d4a7a5933fc68cae3a4f2667) (Angular v4 - Beta). The demo app is currently running version `2.4` which is why we see the issue on the demo app as well. 

Please make sure to use `Angular >= 4`.

**Comment by feeloor** [comment]
We've now updated the example application to Angular 8, which solved the issue. 
Please give it a new try, and feel free to reopen this issue if there still are issues. 

Thanks.

**Comment by yallen011** [comment]
fixed with (PR #3)[https://github.com/rangle/augury.rangle.io/pull/3] in the (augury.rangle.io)[https://github.com/rangle/augury.rangle.io] repo
