### ISSUE TITLE
TypeError: (t.__annotations__ || []).find is not a function

### ISSUE THREAD

**Issue by MRH4287** [rangle/augury#1387]
Augury version (required): 1.23.0 (Canary)
Angular version (required): 6.1.10
Date: 05.08.2018
OS: Windows 10

Description of issue:
We have a rather compley Angular application.
At some point Augury started throwing Exceptions when we tried to use it.
(see below for StackTrace)

As i don't know what causes this error, i can't provide a sample repository.

Because of the error and the mentioned `__annotations__` it is maybe important to note that we are using custom Decorators in our application.

Steps to reproduce:

1. Open Augury
2. Ispect a Component
3. Switch between Elements

Additional details:

```
TypeError: (t.__annotations__ || []).find is not a function
    at Object.e.componentMetadata (chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:47549)
    at chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:173949
    at i (chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33293)
    at chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33468
    at Array.forEach (<anonymous>)
    at i (chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33441)
    at chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33364
    at Array.forEach (<anonymous>)
    at i (chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33335)
    at chrome-extension://leechohfifidanmkioncamdcibhmmcji/build/backend.js:31:33468
```

![image](https://user-images.githubusercontent.com/647258/57362969-47734500-7180-11e9-8bfe-3043559d554c.png)

**Comment by zoltan-nz** [comment]
Augury version (required): 1.23.0
Angular version (required): 8.2.14
Date: 19.01.2020
OS: macOS Catalina

Description of issue:

Simple hello world Angular application. Any click in the Augury console triggers the following error.

![image](https://user-images.githubusercontent.com/1009783/72679643-0f494200-3b16-11ea-8293-716f84df210e.png)
