### ISSUE TITLE
uncaught exception preventing augury from continuing

### ISSUE THREAD

**Issue by mhthompson86** [rangle/augury#1415]
Augury: 1.23.0
Date: Wed, 13 Nov 2019 13:27:20 GMT
OS: Win32

Description of issue:

TypeError: Cannot redefine property: $$el
    at Function.defineProperty (<anonymous>)
    at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:264689)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:262688
    at M (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260124)
    at tt (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:262287)
    at Object.handleImmediate (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:265281)
    at <anonymous>:1:22

Angular version (required): 8.3.8

**Comment by feeloor** [comment]
This is related to #1324. This is going to be fixed in upcoming release, PR for reference: https://github.com/rangle/augury/pull/1411

**Comment by feeloor** [comment]
Hi @mhthompson86, 
We just released a new version of Augury. Please try that version, and feel free to reopen this issue if you still are having issues.

Thanks.
