### ISSUE TITLE
Just does not load 

### ISSUE THREAD

**Issue by runette** [rangle/augury#1426]
Augury: 1.23.0
Date: Wed, 27 Nov 2019 20:29:56 GMT
OS: MacIntel

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1. Install
2. Try
3.
  TypeError: Reflect.getMetadata is not a function
    at l (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:44797)
    at x (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:46046)
    at Object.e.parseModulesFromRootElement (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:44352)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261858
    at M (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260124)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261814
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:368:26)
    at Zone.run (http://localhost:4200/polyfills.js:133:43)
    at http://localhost:4200/polyfills.js:864:36
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:400:31)

Additional details:

**Comment by yallen011** [comment]
Hi runette, can you please provide more information? Like the following:
- What version of Angular are you using?
- Do you have Angular Ivy enabled?
- Can you share a link to the repo you used to produce the error?

**Comment by pepgrifell** [comment]
It happens the same to me.  
Angular version:  8.2.0
Do you have Angular Ivy enabled? no

I attach a snapshot.
![2019-11-28 11_32_41-DevTools - localhost_4200_](https://user-images.githubusercontent.com/6485894/69799071-dc986280-11d2-11ea-8bd6-04a577a9eb6b.png)

**Comment by feeloor** [comment]
@pepgrifell Are you able to provide an example repo or demo repo we can use to investigate?

**Comment by pepgrifell** [comment]
I'm sorry @feeloor but our code is not open source ...

**Comment by feeloor** [comment]
Okay thank you @pepgrifell. We will look into this issue.

**Comment by janosAtZoneFox** [comment]
I get the same in Chrome. And in Firefox:
Angular version: 7.1.4

![Screenshot 2019-11-29 at 13 03 55](https://user-images.githubusercontent.com/44969614/69870763-d4aaf200-12a8-11ea-822f-b53f662aede7.png)

**Comment by runette** [comment]
Angular 8.2.14.

No Ivy.

Code is not not open source - sorry

I literally just installed to try, opened and got this error message and
then uninstalled. Don't have time to waste debugging this.

**Comment by sumitarora** [comment]
@runette We are looking into the issue. Can you tell if you have `aot` enabled for the build?

**Comment by runette** [comment]
I was running against the ng start debug environment. AOT is not enabled on
the build script at the moment.

**Comment by pepgrifell** [comment]
In my case I have it enabled   (ng serve --aot=true)

**Comment by sumitarora** [comment]
@runette @pepgrifell We just release new version yesterday. Can you check if you are still getting the issue? Thanks

**Comment by janosAtZoneFox** [comment]
> @runette @pepgrifell We just release new version yesterday. Can you check if you are still getting the issue? Thanks

If you meant `Version 1.24.0`, then there's no change: `Reflect.getMetadata is not a function` is still thrown.

Why did you close it???

**Comment by feeloor** [comment]
Sorry @janosAtZoneFox, the issue auto closed when we merged the PR. We are still working on this.

**Comment by janosAtZoneFox** [comment]
> Sorry @janosAtZoneFox, the issue auto closed when we merged the PR. We are still working on this.

Thanks.

**Comment by runette** [comment]
Well - you have got rid of the error message but I cannot see any data in
the tool

[image: Screen Shot 2019-12-05 at 23.13.35.png]

You can see the alpha software at trackbash.co.uk

**Comment by feeloor** [comment]
@runette I built Augury locally from the latest commit on `master`, and I was able to get it working on your website. Are you using the latest version from the Chrome store or are you building Augury locally? 

I'll attach the screenshot below.
<img width="1054" alt="Screen Shot 2019-12-06 at 10 47 28 AM" src="https://user-images.githubusercontent.com/6460563/70313390-d1b68100-1815-11ea-9a27-ee6ff78ab631.png">

**Comment by runette** [comment]
I used the chrome store version - to be honest I did not know I was
supposed to anything else.

**Comment by pepgrifell** [comment]
I upgraded the version to 1.24.0. First time, I didn't see anything in the Augurty tab. Then I closed the browser and started it again and it appeared the error:

        TypeError: Reflect.getMetadata is not a function
    at l (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:118755)
    at x (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:120016)
    at Object.e.parseModulesFromRootElement (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:118310)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:162912
    at k (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:161157)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:46:162865
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2125:30)
    at Zone.run (http://localhost:4200/polyfills.js:1884:47)
    at http://localhost:4200/polyfills.js:2611:40
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2160:35)

**Comment by feeloor** [comment]
@runette No problem, we have a fix for this but it's not released yet. If you'd like to use it until we release a new version with the fix, you will have to run it locally. 
To run the plugin locally (with the latest from master-branch) follow these steps: https://github.com/rangle/augury#building-and-installing-locally.

@pepgrifell I think this is the same error as above, it's most likely related to AOT which we have a fix for but it's not released yet. If you'd like to try the fix you can follow the steps above to build the plugin locally and see if it works.

**Comment by LayZeeDK** [comment]
I found that we need to add this line to `polyfills.ts` to use Augury:
```
import 'core-js/es7/reflect';
```
which means that we need to install `core-js` as a development dependency.

**Comment by janosAtZoneFox** [comment]
Thank you @LayZeeDK,
Now the error reported in this issue is gone. Additionally, I commented out `core-js/es6/date` in `polyfills.ts` to be able to see component states.

However, after one navigation within our application now we get the error below, which was reported as [#1428](https://github.com/rangle/augury/issues/1428) and supposedly fixed with [#1430](https://github.com/rangle/augury/pull/1430). My Augury version is `1.24.1`
Thanks for your help.

```
TypeError: Cannot read property 'nativeElement' of undefined
    at e.displayTree (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1508:97375)
    at e.ngOnChanges (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1508:97049)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1127:6520
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1127:6618
    at hC (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1127:7941)
    at HC (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1134:4317)
    at Object.updateDirectives (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1650:132129)
    at Object.updateDirectives (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1134:1087)
    at pC (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1127:4522)
    at wC (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/frontend.js:1127:11148)
```
