### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by Venipa** [rangle/augury#1428]
Augury version (required): e7a9c09
Angular version (required): 9.0.0-next8
Date: 3th Dec. 2019
OS: Windows 10

```
Description of issue:
        TypeError: Cannot read property 'nativeElement' of undefined
    at RouterTree../src/frontend/components/router-tree/router-tree.ts.RouterTree.render (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:125329:38)
    at RouterTree../src/frontend/components/router-tree/router-tree.ts.RouterTree.ngOnChanges (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:125377:14)
    at checkAndUpdateDirectiveInline (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:29184:19)
    at checkAndUpdateNodeInline (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:37586:20)
    at checkAndUpdateNode (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:37548:16)
    at debugCheckAndUpdateNode (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:38182:38)
    at debugCheckDirectivesFn (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:38142:13)
    at Object.updateDirectives (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:123094:2858)
    at Object.debugUpdateDirectives [as updateDirectives] (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:38134:21)
    at checkAndUpdateView (chrome-extension://mkjcinlcphnfppogbajkkpnodaibidcd/build/frontend.js:37530:14)
```
Steps to reproduce:

1. wind up a 9.0.0-next angular project & e7a9c09 augury build
2. upon loading open tab in dev tools

Additional details:

**Comment by feeloor** [comment]
Hi @Venipa,

To help us further investigate, I have a few questions:
- Are you using Ivy? 
- Do you have AOT enabled?

Thanks

**Comment by Venipa** [comment]
- Ivy is disabled
- AOT is enabled but i imported core-js/es7/reflect in my dev polyfills

**Comment by feeloor** [comment]
Okay thank you @Venipa. We will look into this issue.

**Comment by feeloor** [comment]
@Venipa We just merged a fix for this, please try again and feel free to reopen this issue if you still experience problems.
