### ISSUE TITLE
TypeError: n.isStable.pipe is not a function 

### ISSUE THREAD

**Issue by PuriaRad** [rangle/augury#1450]
Augury: 1.24.1
Date: Sun, 26 Jan 2020 07:32:28 GMT
OS: Win64
Angular version (required): 4.3.5

As I start augury extension, this error occurs: 

```
        TypeError: n.isStable.pipe is not a function
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:35531
    at C (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:33708)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:35416
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:11851:26)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (http://localhost:4200/polyfills.bundle.js:11601:43)
    at http://localhost:4200/polyfills.bundle.js:12291:57
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:11884:31)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:11651:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:12055:35)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask (http://localhost:4200/polyfills.bundle.js:11962:21)
```

I tried to add or remove some Polyfills to the project, but none of them worked. Also, adding or removing enableDebugTools to main.ts did not help.

**Comment by hrsiddareddy** [comment]
Hi 
I am also facing the same issue please suggest.
Regards
H S

**Comment by lba-ben** [comment]
Same error, is Augury not usable on Angular 4.x projects?

**Comment by Smeagolworms4** [comment]
+1
