### ISSUE TITLE
Unable to find context associated with [object HTMLDivElement] ; Zone: <root> ; Task: setTimeout ; Value: Error: Unable to find context associated with [object HTMLDivElement]

### ISSUE THREAD

**Issue by bilelkh** [rangle/augury#1464]
Augury: 1.25.2
Date: Thu, 02 Apr 2020 01:38:48 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:
Unhandled Promise rejection: Unable to find context associated with [object HTMLDivElement] ; Zone: <root> ; Task: setTimeout ; Value: Error: Unable to find context associated with [object HTMLDivElement]
    at loadLContext (core.js:25468)
    at Object.getDirectives (core.js:25451)
    at backend.js:61
    at Object.e.matchingChildren (backend.js:61)
    at backend.js:61
    at Array.map (<anonymous>)
    at E (backend.js:61)
    at Object.e.transformIvy (backend.js:61)
    at backend.js:61
    at Array.forEach (<anonymous>) Error: Unable to find context associated with [object HTMLDivElement]
    at loadLContext (http://127.0.0.1:4200/vendor.js:70824:15)
    at Object.getDirectives (http://127.0.0.1:4200/vendor.js:70807:40)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25382
    at Object.e.matchingChildren (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25813)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25209
    at Array.map (<anonymous>)
    at E (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25183)
    at Object.e.transformIvy (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25336)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:61:25096
    at Array.forEach (<anonymous>)
api.onUnhandledError @ zone-evergreen.js:659
handleUnhandledRejection @ zone-evergreen.js:681
api.microtaskDrainDone @ zone-evergreen.js:674
drainMicroTaskQueue @ zone-evergreen.js:577
invokeTask @ zone-evergreen.js:485
ZoneTask.invoke @ zone-evergreen.js:470
timer @ zone-evergreen.js:2535
setTimeout (async)
scheduleTask @ zone-evergreen.js:2556
scheduleTask @ zone-evergreen.js:386
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1118
(anonymous) @ zone-evergreen.js:2569
proto.<computed> @ zone-evergreen.js:1433
(anonymous) @ backend.js:61
e.__tryOrUnsub @ backend.js:16
e.next @ backend.js:16
e._next @ backend.js:16
e.next @ backend.js:16
e._next @ backend.js:16
e.next @ backend.js:16
e._subscribe @ backend.js:46
t._trySubscribe @ backend.js:16
e._trySubscribe @ backend.js:16
t.subscribe @ backend.js:16
t.call @ backend.js:16
t.subscribe @ backend.js:16
(anonymous) @ backend.js:61
C @ backend.js:61
(anonymous) @ backend.js:61
invoke @ zone-evergreen.js:365
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:851
invokeTask @ zone-evergreen.js:400
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:570
invokeTask @ zone-evergreen.js:485
ZoneTask.invoke @ zone-evergreen.js:470
timer @ zone-evergreen.js:2535
setTimeout (async)
scheduleTask @ zone-evergreen.js:2556
scheduleTask @ zone-evergreen.js:386
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1118
(anonymous) @ zone-evergreen.js:2569
proto.<computed> @ zone-evergreen.js:1433
(anonymous) @ backend.js:61
C @ backend.js:61
tt @ backend.js:61
(anonymous) @ backend.js:61
C @ backend.js:61
nt @ backend.js:61
(anonymous) @ backend.js:46
e.browserDispatch @ backend.js:46
(anonymous) @ backend.js:46
invokeTask @ zone-evergreen.js:400
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:481
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1633
postMessage (async)
t.messageJumpContext @ content-script.js:1
(anonymous) @ content-script.js:1
(anonymous) @ content-script.js:1
(anonymous) @ content-script.js:1
Show 13 more frames

**Comment by trfulcher** [comment]
Yeah I get this also on my first attempt to use Augury.
It detects I'm using Angular v9.1.0 but then throws this error.
However a trivial V8.2.14 application works fine so something in v9??

**Comment by coder80s** [comment]
This is related to v9 on forwards (I've reproduce this issue only in 9.0.0 on forwards, may it happen due to Ivy?

**Comment by cwadrupldijjit** [comment]
This seems to be the same issue as #1456.

**Comment by s001dxp** [comment]
I'm using chrome and get this in ng9 as well. I got tens of thousands of this same error in seconds and it caused developer tools to crash. Now everytime I open dev tools the errors start piling up. I had to uninstall the plugin.

**Comment by cwadrupldijjit** [comment]
@s001dxp, I actually put a workaround in the linked issue if you haven't seen it already.  I think the best experience would be to not have to worry about the bug, but that seems like it should be the best way in the meantime.

**Comment by s001dxp** [comment]
Got it, thanks

**Comment by WilldelaVega777** [comment]
Just a question,  Will there *ever* be a version of Augury to provide support for all the Angular 10 goodies? (read Ivy, etc).  Please let me know so I can stay tunned or drop once for all every hope I have in this once upon a time magnificent tool.

**Comment by SandeepBalachandran** [comment]
@WilldelaVega777  #1483  . I think the officials are no longer maintaining the repo. They have other plans as you can see in the angular roadmap

**Comment by tndungu** [comment]
Getting this error on Angular 10

**Comment by hikaru150s** [comment]
Breaks on Angular v11.1.1

**Comment by WuglyakBolgoink** [comment]
Breaks on Angular v11.2.3

**Comment by di3mat** [comment]
Breaks on Angular v11.2.5. 
I think they have stopped updating!

**Comment by juanchavezlive** [comment]
Breaks on Angular 11.2.7 

Augury is dead

**Comment by challengeromar97** [comment]
Breaks on Angular v11.2.8
