### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Matmo10** [rangle/augury#964]
I get this error inconsistently when using augury:

```
Uncaught TypeError: Cannot read property '0' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6514:115
    at Array.reduce (native)
    at resolveNgModuleDecoratorConfig (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6513:30)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6627:42
    at Array.forEach (native)
    at _parseModule (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6622:22)
    at Object.exports.parseModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6521:15)
    at parseInitialModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9405:43)
    at ZoneDelegate.invokeTask (webpack:///./~/zone.js/dist/zone.js?:275:35)
    at Zone.runTask (webpack:///./~/zone.js/dist/zone.js?:151:47)
    at ZoneTask.invoke (webpack:///./~/zone.js/dist/zone.js?:345:33)
    at data.args.(anonymous function) (webpack:///./~/zone.js/dist/zone.js?:1376:25)
```

It seems to be coming from this generated code:
```
	exports.AUGURY_TOKEN_ID_METADATA_KEY = '__augury_token_id';
	var resolveNgModuleDecoratorConfig = function (m) {
	    if (m.decorators) {
	        return m.decorators.reduce(function (prev, curr, idx, decorators) {
	            return prev ? prev : decorators[idx].type.prototype.toString() === '@NgModule' ? decorators[idx].args[0] : null;
	        }, null);
	    }
	    return Reflect.getMetadata('annotations', m).find(function (decorator) { return decorator.toString() === '@NgModule'; });
	};
```

Apparently `decorators[idx].args` is undefined at some point.

![img](http://i.imgur.com/3dmpAE1.png)

Let me know what else I can do to help.

**Comment by Svoig** [comment]
Running into the same problem, starting yesterday.  When I step through, decorators[idx].args does indeed eventually become undefined.

![augury_bug](https://cloud.githubusercontent.com/assets/12769177/22837614/389c18e2-ef76-11e6-9d45-47d79cabc566.png)

**Comment by stevenkampen** [comment]
@Matmo10 @Svoig This should be fixed in v1.2.11. Can you guys confirm?

**Comment by Matmo10** [comment]
@stevenkampen I just updated to 1.2.11 and tried - haven't been able to reproduce it anymore. 👍

**Comment by stevenkampen** [comment]
@Matmo10 Excellent. Thanks for confirming!

@Svoig I'm going to close this now assuming that it's also fixed for you, but let me know if that isn't the case somehow.
